os:
  - linux
language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:elt/libsodium
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq --yes install gcc g++ make libssl-dev libsodium-dev

script:
  - cargo build --verbose
  - cargo build --examples
  - cargo test --examples
  - cargo doc