
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false

matrix:
  include:
  - os: linux
    rust: nightly
  - os: linux
    rust: stable
  
script:
  - cargo build --verbose
  - cargo build --examples
  - cargo test --examples
  - cargo doc