[package]
name = "branca"
description = "A Rust implementation of the branca specification, a JWT alternative."
version = "0.1.1"
authors = ["return"]
keywords = ["fernet", "branca", "crypto", "jwt"]
categories = ["cryptography"]
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/branca"

[dependencies]
base-x = "0.2.3"
byteorder = "1.2.7"
chrono = { version = "0.4.6", features = ["serde"] }
# Will change this to point either sodiumoxide or ring release that supports XChaCha20-Poly1305 in the next release.
# In the meantime, use a local version of sodiumoxide-xchacha20poly1305.
sodiumoxide-xchacha20poly1305 = {version = "^0.1.0"}

[[example]]
name = "example"
path = "test/main.rs"